### PR TITLE
Kernel Storage V2

### PR DESCRIPTION
**Pull request by xinyazhang**
The Kernel Storage V2 achieves the following goals

Major changes:

* Move GPU kernel image to separate files​
    + Now organized as `aotriton.images/<vendor>-<arch>/<kernel_family>/<kernel_name>/FONLY__<functionals>___<GPU>.aks2'`
        - `<GPU>` can be a family of GPUs, e.g., `MI300X／MI300A／MI325X`
    + This enables per-architecture delivery
    + No more linking errors when binaries are bloated.
* Introduce `AKS2` file format to compress GPU kernels with LZMA. Reduce the total package down to 200MB (MI200/300/Navi31)
    + AKS2 means "Aotriton Kernel Storage version 2"
    + LZMA is picked over Zstandard for much better compression ratio (~7% vs ~12%) and acceptable performance (<0.1s)
* Look up kernel image relative to the `.so` file (achieved through `dladdr`)
* Can only build the C++ part by setting `cmake` option `AOTRITON_NOIMAGE_MODE` to `ON` 

Minor changes:
* Release GIL in pybind11
* `aks2.py` tool is added to create `AKS2` file.
* Update Triton compiler to Oct/23/2024
    + This is to fix bug ```Assertion `(!LeaveBefore || Idx <= LeaveBefore) && "Interference"' failed```
    + See https://github.com/llvm/llvm-project/issues/109294 for more details

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@ethanwee1 to help with testing of building AOTriton using this PR with and without `AOTRITON_NOIMAGE_MODE=ON`

**Comment by ethanwee1** [comment]
Tested with these commands to build 
`aotriton-e278d4a853170c7a9063cfe847419414cb7b62b6-manylinux_2_28_x86_64-rocm6.2-shared.tar.gz`

Commands:

```
git clone https://github.com/ROCm/aotriton.git
cd aotriton/
git checkout xinyazhang/manylinux_2_28-dockerfile
cd dockerfile/
export AMDGPU_INSTALLER=https://repo.radeon.com/amdgpu-install/6.2.4/el/8.10/amdgpu-install-6.2.60204-1.el8.noarch.rpm
mkdir -p output
TRITON_LLVM_HASH="b5cc222d" AOTRITON_NOIMAGE_MODE=ON bash build.sh input tmpfs output e278d4a853170c7a9063cfe847419414cb7b62b6 "MI300X;MI200" 2>&1 | tee buildlog2.log
tar tvf output/*.tar*
```

Output:
Size: 107MB
[aotriton-e278d4a853170c7a9063cfe847419414cb7b62b6-manylinux_2_28_x86_64-rocm6.2-shared_WITHAOTRITON_NOIMAGE_MODE_ON.txt](https://github.com/user-attachments/files/17740386/aotriton-e278d4a853170c7a9063cfe847419414cb7b62b6-manylinux_2_28_x86_64-rocm6.2-shared_WITHAOTRITON_NOIMAGE_MODE_ON.txt)
[buildlog2.log](https://github.com/user-attachments/files/17740387/buildlog2.log)

**Comment by xinyazhang** [comment]
> > Output: Size: 107MB [aotriton-e278d4a853170c7a9063cfe847419414cb7b62b6-manylinux_2_28_x86_64-rocm6.2-shared_WITHAOTRITON_NOIMAGE_MODE_ON.txt](https://github.com/user-attachments/files/17740386/aotriton-e278d4a853170c7a9063cfe847419414cb7b62b6-manylinux_2_28_x86_64-rocm6.2-shared_WITHAOTRITON_NOIMAGE_MODE_ON.txt) [buildlog2.log](https://github.com/user-attachments/files/17740387/buildlog2.log)
> 
> @ethanwee1 This doesn't look right. The tarball size and txt file indicate that kernel images are still being built. Either your experiement was faulty or the AOTRITON_NOIMAGE_MODE logic is faulty. @xinyazhang, thoughts?

I think you need to download the log for review since it's rather large and likely get truncated. The trailing `-- Install configuration: "Release"` lines have indicated this project installed to the target directory.

The size is right. I only specified two architectures and 100MB is the right size for 2 arches under Kernel Storage V2.

**Comment by xinyazhang** [comment]
`AOTRITON_NOIMAGE_MODE` will be tested in another dockerfile related PRs

**Comment by jithunnair-amd** [comment]
> > > Output: Size: 107MB [aotriton-e278d4a853170c7a9063cfe847419414cb7b62b6-manylinux_2_28_x86_64-rocm6.2-shared_WITHAOTRITON_NOIMAGE_MODE_ON.txt](https://github.com/user-attachments/files/17740386/aotriton-e278d4a853170c7a9063cfe847419414cb7b62b6-manylinux_2_28_x86_64-rocm6.2-shared_WITHAOTRITON_NOIMAGE_MODE_ON.txt) [buildlog2.log](https://github.com/user-attachments/files/17740387/buildlog2.log)
> > 
> > 
> > @ethanwee1 This doesn't look right. The tarball size and txt file indicate that kernel images are still being built. Either your experiement was faulty or the AOTRITON_NOIMAGE_MODE logic is faulty. @xinyazhang, thoughts?
> 
> I think you need to download the log for review since it's rather large and likely get truncated if viewing with a browser. The trailing `-- Install configuration: "Release"` lines have indicated this project installed to the target directory.
> 
> The size is right. I only specified two architectures and 100MB is about the right size for 2 arches under Kernel Storage V2.
> 
> (However non-square causal masks added some more kernels and two arches ~= 130MB when releasing 0.8b)

Just to resolve the confusion here, I was referring to Ethan's initial numbers for the `AOTRITON_NOIMAGE_MODE=ON` build. He corrected his build steps thereafter and updated his comment to show that the new size is only 1.6MB, which is what I expected. So, in summary, looks like `AOTRITON_NOIMAGE_MODE=ON` is working as expected.

**Pull request merged**
